services:
    zookeeper:
        image: bitnami/zookeeper:3.9
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"

    kafka:
        image: bitnami/kafka:3.6
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            ALLOW_PLAINTEXT_LISTENER: "yes"
        depends_on:
            - zookeeper

    postgres:
        image: postgres:15
        container_name: postgresql
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: finaldb
        ports:
            - "5432:5432"
        networks:
            - app-network

    redis:
        image: redis:7
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network
        command: [ "redis-server", "--save", "", "--appendonly", "no" ]

networks:
    app-network:
        driver: bridge
