spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/redisCaching
        username: admin
        password: admin

    data:
        redis:
            host: redis
            port: 6379

    kafka:
        bootstrap-servers: kafka:9092
        consumer:
            group-id: demo-group