apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
                - name: kafka
                  image: bitnami/kafka:4.0.0
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_ENABLE_KRAFT
                        value: "yes"
                      - name: KAFKA_CFG_NODE_ID
                        value: "1"
                      - name: KAFKA_CFG_PROCESS_ROLES
                        value: "broker,controller"
                      - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
                        value: "1@kafka:9093"
                      - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
                        value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
                      - name: KAFKA_CFG_LISTENERS
                        value: "PLAINTEXT://:9092,CONTROLLER://:9093"
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: "PLAINTEXT://kafka:9092"
                      - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
                        value: "CONTROLLER"
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
---
apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    selector:
        app: kafka
    ports:
        - name: kafka
          port: 9092
          targetPort: 9092
