apiVersion: v1
kind: Service
metadata:
    name: blogapp-service
spec:
    type: NodePort
    selector:
        app: blogapp
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30080
