apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: spring-app
    template:
        metadata:
            labels:
                app: spring-app
        spec: 
            containers:
                - name: spring-app
                  image: sreeyuktha/blogapp-app:latest
                  ports:
                      - containerPort: 8080
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        value: docker
                      - name: SPRING_DATASOURCE_URL
                        value: jdbc:postgresql://postgres:5432/mydatabase
                      - name: SPRING_DATASOURCE_USERNAME
                        value: myuser
                      - name: SPRING_DATASOURCE_PASSWORD
                        value: secret
                      - name: SPRING_REDIS_HOST
                        value: redis
                      - name: SPRING_REDIS_PORT
                        value: "6379"
                      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
                        value: kafka:9092
                      - name: SPRING_KAFKA_CONSUMER_GROUP_ID
                        value: user-consumer-group
                      - name: SPRING_ELASTICSEARCH_URIS
                        value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
    name: spring-app-service
spec:
    selector:
        app: spring-app
    ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
    type: NodePort
